# Name of your site
name: GUS

# Short description and will be used in the RSS feed from https://github.com/snaptortoise/jekyll-rss-feeds
description: Google Spreadsheets and Leaflet

# Your name, as you want it to appear underneath each post and in the footer
author: Sam Matthews

baseurl:
url: http://mapsam.com/gus/

#### Under the Hood Stuff #####

markdown: kramdown
